### ISSUE TITLE
Monochrome challenge makes palette scrollbar appear, deletes colors, isn't working

### ISSUE THREAD

**Issue by Maxsl24** [toobeeh/skribbltypo#326]
When activating the Monochrome Challenge, the Scrollbar below the currently selected palette appears, regardless of the number of Columns of the currently selected palette:

![Image](https://github.com/user-attachments/assets/7f48746e-8cad-4c67-8f28-aa8ffb37936d)

Additionally, when using a palette with only one color, the Monochrome Challenge either gives you the one color as a large bar (expected, but also with unwanted scollbar):

![Image](https://github.com/user-attachments/assets/80eeaa4a-a420-4115-b27b-ef4cc6f6a1ab)

or it deletes all colors, making you have no colors to select:

![Image](https://github.com/user-attachments/assets/dc93485a-77a3-4aaa-bba0-01645d19b6f8)

Lastly, when disabling Color Palettes in the Typo Settings, the Monochrome Challenge won't select any colors and doesn't change anything.

![Image](https://github.com/user-attachments/assets/b876da9d-9502-49d9-bddd-f48068e84f45)

![Image](https://github.com/user-attachments/assets/25e3f034-f492-43c8-8711-5f9477e89b38)

**Comment by toobeeh** [comment]
closing because it has been fixed already

**Comment by Maxsl24** [comment]
these issues still exist in the newest version of typo tho :(
